type TagCategory = 'Web Development' | 'Programming Language' | 'Self-Care' | 'Mindset' | 'DevOps' | 'Data Science' | 'Soft Skills' | 'Project Management';

export interface Tag {
  name: string;
  category: TagCategory;
}

export const tags: Tag[] = [
  { name: 'HTML', category: 'Web Development' },
  { name: 'CSS', category: 'Web Development' },
  { name: 'JavaScript', category: 'Web Development' },
  { name: 'React', category: 'Web Development' },
  { name: 'Angular', category: 'Web Development' },
  { name: 'Vue.js', category: 'Web Development' },
  { name: 'Next.js', category: 'Web Development' },
  { name: 'Gatsby', category: 'Web Development' },
  { name: 'Node.js', category: 'Web Development' },
  { name: 'Express.js', category: 'Web Development' },
  { name: 'GraphQL', category: 'Web Development' },
  { name: 'REST API', category: 'Web Development' },
  { name: 'Responsive Design', category: 'Web Development' },
  { name: 'Progressive Web Apps', category: 'Web Development' },
  { name: 'Web Accessibility', category: 'Web Development' },
  { name: 'SEO', category: 'Web Development' },
  { name: 'Web Performance', category: 'Web Development' },
  { name: 'WebSockets', category: 'Web Development' },
  { name: 'Webpack', category: 'Web Development' },
  { name: 'Babel', category: 'Web Development' },

  // Programming Languages
  { name: 'Python', category: 'Programming Language' },
  { name: 'Java', category: 'Programming Language' },
  { name: 'C++', category: 'Programming Language' },
  { name: 'C#', category: 'Programming Language' },
  { name: 'Ruby', category: 'Programming Language' },
  { name: 'Go', category: 'Programming Language' },
  { name: 'Rust', category: 'Programming Language' },
  { name: 'Swift', category: 'Programming Language' },
  { name: 'Kotlin', category: 'Programming Language' },
  { name: 'PHP', category: 'Programming Language' },
  { name: 'TypeScript', category: 'Programming Language' },
  { name: 'Scala', category: 'Programming Language' },
  { name: 'Haskell', category: 'Programming Language' },
  { name: 'Dart', category: 'Programming Language' },
  { name: 'R', category: 'Programming Language' },
  { name: 'MATLAB', category: 'Programming Language' },
  { name: 'Lua', category: 'Programming Language' },
  { name: 'Perl', category: 'Programming Language' },
  { name: 'Groovy', category: 'Programming Language' },
  { name: 'Julia', category: 'Programming Language' },

  // Self-Care
  { name: 'Meditation', category: 'Self-Care' },
  { name: 'Yoga', category: 'Self-Care' },
  { name: 'Exercise', category: 'Self-Care' },
  { name: 'Healthy Eating', category: 'Self-Care' },
  { name: 'Sleep Hygiene', category: 'Self-Care' },
  { name: 'Journaling', category: 'Self-Care' },
  { name: 'Mindfulness', category: 'Self-Care' },
  { name: 'Stress Management', category: 'Self-Care' },
  { name: 'Time Management', category: 'Self-Care' },
  { name: 'Work-Life Balance', category: 'Self-Care' },
  { name: 'Hobbies', category: 'Self-Care' },
  { name: 'Social Connections', category: 'Self-Care' },
  { name: 'Nature Therapy', category: 'Self-Care' },
  { name: 'Aromatherapy', category: 'Self-Care' },
  { name: 'Massage', category: 'Self-Care' },
  { name: 'Digital Detox', category: 'Self-Care' },
  { name: 'Gratitude Practice', category: 'Self-Care' },
  { name: 'Self-Reflection', category: 'Self-Care' },
  { name: 'Hydration', category: 'Self-Care' },
  { name: 'Skincare', category: 'Self-Care' },

  // Mindset
  { name: 'Growth Mindset', category: 'Mindset' },
  { name: 'Positive Thinking', category: 'Mindset' },
  { name: 'Resilience', category: 'Mindset' },
  { name: 'Emotional Intelligence', category: 'Mindset' },
  { name: 'Goal Setting', category: 'Mindset' },
  { name: 'Self-Motivation', category: 'Mindset' },
  { name: 'Adaptability', category: 'Mindset' },
  { name: 'Creativity', category: 'Mindset' },
  { name: 'Critical Thinking', category: 'Mindset' },
  { name: 'Problem Solving', category: 'Mindset' },
  { name: 'Continuous Learning', category: 'Mindset' },
  { name: 'Self-Confidence', category: 'Mindset' },
  { name: 'Empathy', category: 'Mindset' },
  { name: 'Leadership', category: 'Mindset' },
  { name: 'Collaboration', category: 'Mindset' },
  { name: 'Time Perspective', category: 'Mindset' },
  { name: 'Mindfulness', category: 'Mindset' },
  { name: 'Self-Awareness', category: 'Mindset' },
  { name: 'Perseverance', category: 'Mindset' },
  { name: 'Optimism', category: 'Mindset' },

  // DevOps
  { name: 'CI/CD', category: 'DevOps' },
  { name: 'Docker', category: 'DevOps' },
  { name: 'Kubernetes', category: 'DevOps' },
  { name: 'Jenkins', category: 'DevOps' },
  { name: 'Ansible', category: 'DevOps' },
  { name: 'Terraform', category: 'DevOps' },
  { name: 'Git', category: 'DevOps' },
  { name: 'Monitoring', category: 'DevOps' },
  { name: 'Logging', category: 'DevOps' },
  { name: 'Cloud Computing', category: 'DevOps' },

  // Data Science
  { name: 'Machine Learning', category: 'Data Science' },
  { name: 'Deep Learning', category: 'Data Science' },
  { name: 'Neural Networks', category: 'Data Science' },
  { name: 'Big Data', category: 'Data Science' },
  { name: 'Data Visualization', category: 'Data Science' },
  { name: 'Statistical Analysis', category: 'Data Science' },
  { name: 'Natural Language Processing', category: 'Data Science' },
  { name: 'Computer Vision', category: 'Data Science' },
  { name: 'Predictive Modeling', category: 'Data Science' },
  { name: 'Data Mining', category: 'Data Science' },

  // Soft Skills
  { name: 'Communication', category: 'Soft Skills' },
  { name: 'Teamwork', category: 'Soft Skills' },
  { name: 'Adaptability', category: 'Soft Skills' },
  { name: 'Problem-Solving', category: 'Soft Skills' },
  { name: 'Time Management', category: 'Soft Skills' },
  { name: 'Conflict Resolution', category: 'Soft Skills' },
  { name: 'Leadership', category: 'Soft Skills' },
  { name: 'Emotional Intelligence', category: 'Soft Skills' },
  { name: 'Creativity', category: 'Soft Skills' },
  { name: 'Critical Thinking', category: 'Soft Skills' },

  // Project Management
  { name: 'Agile', category: 'Project Management' },
  { name: 'Scrum', category: 'Project Management' },
  { name: 'Kanban', category: 'Project Management' },
  { name: 'Waterfall', category: 'Project Management' },
  { name: 'Risk Management', category: 'Project Management' },
  { name: 'Stakeholder Management', category: 'Project Management' },
  { name: 'Resource Allocation', category: 'Project Management' },
  { name: 'Budgeting', category: 'Project Management' },
  { name: 'Project Planning', category: 'Project Management' },
  { name: 'Quality Management', category: 'Project Management' },
];
